import Head from 'next/head'
import Link from 'next/link'
import Heading from '/components/Heading.js'
import Header from '/components/Header.js'
import React from 'react'
import ContactForm from '../components/ContactForm'


export default function Contact() {

  

  if(typeof document != 'undefined'){
    document.querySelector('body').classList.add('styleBackGround');
  }

  return(

    <div className="styleBackground" >

      <Head>
        <title>Midwestern: Embedding Success </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500;700&display=swap" rel="stylesheet" /> 
      
         


      </Head>

      <Header  links={[{href:'/',title:'home'}]}  />


      <main className="mainContact">
      
        <div class="contactLeft" >
          <Heading />

          <div  >
            
            <p >
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do dos eiusmod tempor incididunt ut labore et trace dolore magna aliqua.
            </p>
            <p>
                Proin sagittis nisl rhoncus mattis rhoncus. At augue eget arcu dictum varius duis at consectetur lorem.
            </p>
          </div>
        </div>

        <section className="contactFormContainer">
          
          <div >

            <ContactForm />
          </div>
            
        </section>

      </main>

    </div>


  )
  

}


