import Head from 'next/head'
import Link from 'next/link'
import Heading from '/components/Heading.js'
import React from 'react'


export default function Contact() {

    
  return(

    <div  >

      <Head>
        <title>Midwestern: Embedding Success </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500;700&display=swap" rel="stylesheet" /> 
      </Head>

      <header className="  contactHeader ">

        <div class="mainHeader">
          <img src="/images/Logo.png" class="logo" alt="Logo"  />

          <Link href="/">
            <a className="headerLink" >home</a>
          </Link>


        </div>
        
      </header>

      <main className="mainContact">
      
        <div  >
          <Heading />
          <div style={{width:473}}>
            
            <p >
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do dos eiusmod tempor incididunt ut labore et trace dolore magna aliqua.
            </p>
            <p>
                Proin sagittis nisl rhoncus mattis rhoncus. At augue eget arcu dictum varius duis at consectetur lorem.
            </p>
          </div>
        </div>

        <div className="whiteBox">
            <span    >
              this is a work in progress.   
            </span> 
        </div>

      </main>

    </div>


  )
  

}
